/**
 * generated by Xtext 2.16.0
 */
package com.ifs.lang.projection.scoping;

import com.ifs.lang.projection.scoping.AbstractProjectionLangScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ProjectionLangScopeProvider extends AbstractProjectionLangScopeProvider {
}
