/**
 * generated by Xtext 2.16.0
 */
package com.ifs.lang.projection.projectionLang.impl;

import com.ifs.lang.projection.projectionLang.Component;
import com.ifs.lang.projection.projectionLang.ProjectionLangPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Component</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ComponentImpl extends TypeImpl implements Component
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComponentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ProjectionLangPackage.Literals.COMPONENT;
  }

} //ComponentImpl
