/**
 * generated by Xtext 2.16.0
 */
package com.ifs.lang.projection.projectionLang.impl;

import com.ifs.lang.projection.projectionLang.Layer;
import com.ifs.lang.projection.projectionLang.ProjectionLangPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Layer</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class LayerImpl extends TypeImpl implements Layer
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LayerImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ProjectionLangPackage.Literals.LAYER;
  }

} //LayerImpl
