/*
 * generated by Xtext 2.16.0
 */
package com.ifs.lang.projection.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractProjectionLangScopeProvider extends DelegatingScopeProvider {
}
