/*
 * generated by Xtext 2.16.0
 */
package com.ifs.lang.projection


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ProjectionLangStandaloneSetup extends ProjectionLangStandaloneSetupGenerated {

	def static void doSetup() {
		new ProjectionLangStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
