/**
 * generated by Xtext 2.16.0
 */
package com.ifs.lang.projection;

import com.ifs.lang.projection.ProjectionLangStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ProjectionLangStandaloneSetup extends ProjectionLangStandaloneSetupGenerated {
  public static void doSetup() {
    new ProjectionLangStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
