/**
 * generated by Xtext 2.16.0
 */
package com.ifs.lang.projection;

import com.ifs.lang.projection.AbstractProjectionLangRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ProjectionLangRuntimeModule extends AbstractProjectionLangRuntimeModule {
}
