/**
 * generated by Xtext 2.16.0
 */
package com.ifs.lang.projection.projectionLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Category</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.ifs.lang.projection.projectionLang.ProjectionLangPackage#getCategory()
 * @model
 * @generated
 */
public interface Category extends Type
{
} // Category
