/**
 * generated by Xtext 2.16.0
 */
package com.ifs.lang.projection.projectionLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entityset</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.ifs.lang.projection.projectionLang.Entityset#getEntity <em>Entity</em>}</li>
 * </ul>
 *
 * @see com.ifs.lang.projection.projectionLang.ProjectionLangPackage#getEntityset()
 * @model
 * @generated
 */
public interface Entityset extends Type
{
  /**
   * Returns the value of the '<em><b>Entity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entity</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity</em>' attribute.
   * @see #setEntity(String)
   * @see com.ifs.lang.projection.projectionLang.ProjectionLangPackage#getEntityset_Entity()
   * @model
   * @generated
   */
  String getEntity();

  /**
   * Sets the value of the '{@link com.ifs.lang.projection.projectionLang.Entityset#getEntity <em>Entity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity</em>' attribute.
   * @see #getEntity()
   * @generated
   */
  void setEntity(String value);

} // Entityset
