/**
 * generated by Xtext 2.16.0
 */
package com.ifs.lang.projection.projectionLang;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.ifs.lang.projection.projectionLang.ProjectionLangFactory
 * @model kind="package"
 * @generated
 */
public interface ProjectionLangPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "projectionLang";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ifs.com/lang/projection/ProjectionLang";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "projectionLang";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ProjectionLangPackage eINSTANCE = com.ifs.lang.projection.projectionLang.impl.ProjectionLangPackageImpl.init();

  /**
   * The meta object id for the '{@link com.ifs.lang.projection.projectionLang.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ifs.lang.projection.projectionLang.impl.ModelImpl
   * @see com.ifs.lang.projection.projectionLang.impl.ProjectionLangPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.ifs.lang.projection.projectionLang.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ifs.lang.projection.projectionLang.impl.TypeImpl
   * @see com.ifs.lang.projection.projectionLang.impl.ProjectionLangPackageImpl#getType()
   * @generated
   */
  int TYPE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__NAME = 0;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.ifs.lang.projection.projectionLang.impl.ProjectionImpl <em>Projection</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ifs.lang.projection.projectionLang.impl.ProjectionImpl
   * @see com.ifs.lang.projection.projectionLang.impl.ProjectionLangPackageImpl#getProjection()
   * @generated
   */
  int PROJECTION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECTION__NAME = TYPE__NAME;

  /**
   * The number of structural features of the '<em>Projection</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECTION_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.ifs.lang.projection.projectionLang.impl.ComponentImpl <em>Component</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ifs.lang.projection.projectionLang.impl.ComponentImpl
   * @see com.ifs.lang.projection.projectionLang.impl.ProjectionLangPackageImpl#getComponent()
   * @generated
   */
  int COMPONENT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__NAME = TYPE__NAME;

  /**
   * The number of structural features of the '<em>Component</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.ifs.lang.projection.projectionLang.impl.LayerImpl <em>Layer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ifs.lang.projection.projectionLang.impl.LayerImpl
   * @see com.ifs.lang.projection.projectionLang.impl.ProjectionLangPackageImpl#getLayer()
   * @generated
   */
  int LAYER = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYER__NAME = TYPE__NAME;

  /**
   * The number of structural features of the '<em>Layer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYER_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.ifs.lang.projection.projectionLang.impl.DescriptionImpl <em>Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ifs.lang.projection.projectionLang.impl.DescriptionImpl
   * @see com.ifs.lang.projection.projectionLang.impl.ProjectionLangPackageImpl#getDescription()
   * @generated
   */
  int DESCRIPTION = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION__NAME = TYPE__NAME;

  /**
   * The number of structural features of the '<em>Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.ifs.lang.projection.projectionLang.impl.CategoryImpl <em>Category</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ifs.lang.projection.projectionLang.impl.CategoryImpl
   * @see com.ifs.lang.projection.projectionLang.impl.ProjectionLangPackageImpl#getCategory()
   * @generated
   */
  int CATEGORY = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CATEGORY__NAME = TYPE__NAME;

  /**
   * The number of structural features of the '<em>Category</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CATEGORY_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.ifs.lang.projection.projectionLang.impl.EntitysetImpl <em>Entityset</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ifs.lang.projection.projectionLang.impl.EntitysetImpl
   * @see com.ifs.lang.projection.projectionLang.impl.ProjectionLangPackageImpl#getEntityset()
   * @generated
   */
  int ENTITYSET = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITYSET__NAME = TYPE__NAME;

  /**
   * The feature id for the '<em><b>Entity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITYSET__ENTITY = TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Entityset</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITYSET_FEATURE_COUNT = TYPE_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link com.ifs.lang.projection.projectionLang.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see com.ifs.lang.projection.projectionLang.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link com.ifs.lang.projection.projectionLang.Model#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see com.ifs.lang.projection.projectionLang.Model#getElements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Elements();

  /**
   * Returns the meta object for class '{@link com.ifs.lang.projection.projectionLang.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see com.ifs.lang.projection.projectionLang.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for the attribute '{@link com.ifs.lang.projection.projectionLang.Type#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.ifs.lang.projection.projectionLang.Type#getName()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Name();

  /**
   * Returns the meta object for class '{@link com.ifs.lang.projection.projectionLang.Projection <em>Projection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Projection</em>'.
   * @see com.ifs.lang.projection.projectionLang.Projection
   * @generated
   */
  EClass getProjection();

  /**
   * Returns the meta object for class '{@link com.ifs.lang.projection.projectionLang.Component <em>Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component</em>'.
   * @see com.ifs.lang.projection.projectionLang.Component
   * @generated
   */
  EClass getComponent();

  /**
   * Returns the meta object for class '{@link com.ifs.lang.projection.projectionLang.Layer <em>Layer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Layer</em>'.
   * @see com.ifs.lang.projection.projectionLang.Layer
   * @generated
   */
  EClass getLayer();

  /**
   * Returns the meta object for class '{@link com.ifs.lang.projection.projectionLang.Description <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Description</em>'.
   * @see com.ifs.lang.projection.projectionLang.Description
   * @generated
   */
  EClass getDescription();

  /**
   * Returns the meta object for class '{@link com.ifs.lang.projection.projectionLang.Category <em>Category</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Category</em>'.
   * @see com.ifs.lang.projection.projectionLang.Category
   * @generated
   */
  EClass getCategory();

  /**
   * Returns the meta object for class '{@link com.ifs.lang.projection.projectionLang.Entityset <em>Entityset</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entityset</em>'.
   * @see com.ifs.lang.projection.projectionLang.Entityset
   * @generated
   */
  EClass getEntityset();

  /**
   * Returns the meta object for the attribute '{@link com.ifs.lang.projection.projectionLang.Entityset#getEntity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Entity</em>'.
   * @see com.ifs.lang.projection.projectionLang.Entityset#getEntity()
   * @see #getEntityset()
   * @generated
   */
  EAttribute getEntityset_Entity();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ProjectionLangFactory getProjectionLangFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.ifs.lang.projection.projectionLang.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ifs.lang.projection.projectionLang.impl.ModelImpl
     * @see com.ifs.lang.projection.projectionLang.impl.ProjectionLangPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENTS = eINSTANCE.getModel_Elements();

    /**
     * The meta object literal for the '{@link com.ifs.lang.projection.projectionLang.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ifs.lang.projection.projectionLang.impl.TypeImpl
     * @see com.ifs.lang.projection.projectionLang.impl.ProjectionLangPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__NAME = eINSTANCE.getType_Name();

    /**
     * The meta object literal for the '{@link com.ifs.lang.projection.projectionLang.impl.ProjectionImpl <em>Projection</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ifs.lang.projection.projectionLang.impl.ProjectionImpl
     * @see com.ifs.lang.projection.projectionLang.impl.ProjectionLangPackageImpl#getProjection()
     * @generated
     */
    EClass PROJECTION = eINSTANCE.getProjection();

    /**
     * The meta object literal for the '{@link com.ifs.lang.projection.projectionLang.impl.ComponentImpl <em>Component</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ifs.lang.projection.projectionLang.impl.ComponentImpl
     * @see com.ifs.lang.projection.projectionLang.impl.ProjectionLangPackageImpl#getComponent()
     * @generated
     */
    EClass COMPONENT = eINSTANCE.getComponent();

    /**
     * The meta object literal for the '{@link com.ifs.lang.projection.projectionLang.impl.LayerImpl <em>Layer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ifs.lang.projection.projectionLang.impl.LayerImpl
     * @see com.ifs.lang.projection.projectionLang.impl.ProjectionLangPackageImpl#getLayer()
     * @generated
     */
    EClass LAYER = eINSTANCE.getLayer();

    /**
     * The meta object literal for the '{@link com.ifs.lang.projection.projectionLang.impl.DescriptionImpl <em>Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ifs.lang.projection.projectionLang.impl.DescriptionImpl
     * @see com.ifs.lang.projection.projectionLang.impl.ProjectionLangPackageImpl#getDescription()
     * @generated
     */
    EClass DESCRIPTION = eINSTANCE.getDescription();

    /**
     * The meta object literal for the '{@link com.ifs.lang.projection.projectionLang.impl.CategoryImpl <em>Category</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ifs.lang.projection.projectionLang.impl.CategoryImpl
     * @see com.ifs.lang.projection.projectionLang.impl.ProjectionLangPackageImpl#getCategory()
     * @generated
     */
    EClass CATEGORY = eINSTANCE.getCategory();

    /**
     * The meta object literal for the '{@link com.ifs.lang.projection.projectionLang.impl.EntitysetImpl <em>Entityset</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ifs.lang.projection.projectionLang.impl.EntitysetImpl
     * @see com.ifs.lang.projection.projectionLang.impl.ProjectionLangPackageImpl#getEntityset()
     * @generated
     */
    EClass ENTITYSET = eINSTANCE.getEntityset();

    /**
     * The meta object literal for the '<em><b>Entity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITYSET__ENTITY = eINSTANCE.getEntityset_Entity();

  }

} //ProjectionLangPackage
