/**
 * generated by Xtext 2.16.0
 */
package com.ifs.lang.projection.projectionLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Projection</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.ifs.lang.projection.projectionLang.ProjectionLangPackage#getProjection()
 * @model
 * @generated
 */
public interface Projection extends Type
{
} // Projection
