/**
 * generated by Xtext 2.16.0
 */
package com.ifs.lang.projection.validation;

import com.ifs.lang.projection.validation.AbstractProjectionLangValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ProjectionLangValidator extends AbstractProjectionLangValidator {
}
