/**
 * generated by Xtext 2.16.0
 */
package com.ifs.lang.projection.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.ifs.lang.projection.ProjectionLangRuntimeModule;
import com.ifs.lang.projection.ProjectionLangStandaloneSetup;
import com.ifs.lang.projection.ide.ProjectionLangIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ProjectionLangIdeSetup extends ProjectionLangStandaloneSetup {
  @Override
  public Injector createInjector() {
    ProjectionLangRuntimeModule _projectionLangRuntimeModule = new ProjectionLangRuntimeModule();
    ProjectionLangIdeModule _projectionLangIdeModule = new ProjectionLangIdeModule();
    return Guice.createInjector(Modules2.mixin(_projectionLangRuntimeModule, _projectionLangIdeModule));
  }
}
