/**
 * generated by Xtext 2.16.0
 */
package com.ifs.lang.projection.ide;

import com.ifs.lang.projection.ide.AbstractProjectionLangIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ProjectionLangIdeModule extends AbstractProjectionLangIdeModule {
}
